# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: RAMP tests

on:
  push:
    branches: [ "main", "development", "joss-paper"]
  pull_request:
    branches: [ "main", "development", "joss-paper"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black[jupyter]==24.4.2
    - name: Lint with black
      run: |
        black . --check
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r tests/requirements.txt
    - name: Test with pytest
      run: |
        coverage run -m pytest tests/

    - name: Check test coverage
      run: |
        coverage report -m

    - name: Report to coveralls
      run: |
        coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALL_TOKEN }}
        COVERALLS_SERVICE_NAME: github
