name: Deploy to Test PyPi

on:
  push:
      branches:
        - development
        - main

  pull_request:
    branches:
      - development
      - main
jobs:
  build_and_deploy:
    name: Build the release and deploy to test pypi
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install main dependencies
        run: |
          python -m pip install --upgrade pip twine setuptools wheel
      - name: build distribution
        run: |
          python setup.py sdist bdist_wheel
      - name: test install package
        run: |
          pip install -e .
      - name: Publish distribution 📦 to TestPyPI

        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          password: ${{ secrets.RAMP_TEST}}
          repository-url: https://test.pypi.org/legacy/
